### ISSUE TITLE
https handling sometimes faulty

### ISSUE THREAD

**Issue by velochy** [mitodl/pylti#39]
in common.py:
    # Check header for SSL before selecting the url
    if headers.get('X-Forwarded-Proto', 'http') == 'https':
        url = url.replace('http', 'https', 1)

if url already starts with https://, this will make it into httpss://, screwing up the signature and failing validation.

Simple fix: url.replace('http:','https:',1)

**Comment by amir-qayyum-khan** [comment]
@velochy just fixed it

cc @pdpinch
