### ISSUE TITLE
Student tests using incorrect url

### ISSUE THREAD

**Issue by brianjbeach** [mitodl/pylti#85]
If I understand the intent of these tests, you should be sending the request to /initial_student? rather than /initial_unknown?.  Also, in the first of the two tests you are passing a role of "Staff". Staff is the name used in the decorator, but you should be passing either Administrator or Instructor in the in the request.

https://github.com/mitodl/pylti/blob/5088b1d3a0e7525a32a759397d244c84ae332b73/pylti/tests/test_flask.py#L291-L309

**Comment by pdpinch** [comment]
@brianjbeach Amir opened a PR to fix this. Can you take a look and give us some feedback?
