### ISSUE TITLE
Any plans to support LTI 1.3?

### ISSUE THREAD

**Issue by auraz** [mitodl/pylti#95]

**Comment by jonespm** [comment]
+1 It looks like another library supports 1.3 https://github.com/dmitry-viskov/pylti1.3 but many packages depend on the one (including most of our projects) and I'd like to avoid rewriting.

**Comment by auraz** [comment]
@jonespm Thank you. I reviewed it back then, and also we have same situation :)

**Comment by pdpinch** [comment]
Sorry, no plans. But if you want to open a PR we could review it.

**Comment by auraz** [comment]
> But if you want to open a PR we could review it.

I also can review it ;)

**Comment by auraz** [comment]
Closing as question answered.
